## Introduction to numpy

Numpy is a python library for handling arrays. The word numpy stands for NUMerical PYthon.

What is an array?

An array is a data structure of elements of the same data type stored using the same variable name and accesible through index. Every aray is zero indexed. It helps in memory management

##### Use of array
The elements are all of the same data type.

#### To install numpy
pip install numpy

N/B: If you are using anaconda, then you already have numpy.

The Ndarray is numpy's basic structure for dealing with a collection of the same type.

To create an array from a list,

numpy.array(list)

##### syntax:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

Object is the list to convert to array

dtype - the numpy dtype of elements of resultant array

copy - the list is copied (default)

order - C (row major) of F (column major) or A (any) (default)

subok - By default, returned array forced to be a base class array. If true, sub-classes passed through

ndmin - specifies minimum dimensions of resultant array.

##### Numpy datatypes(dtypes) includes

- bool
- int
- intc
- intp
- int8 (-128 to 127)
- int16 (-32768 to 32768)
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float
- float16
- float32
- float64
- complex
- complex64
- complex128

##### Attributes

- shape: gives the dimension of the array. It can also be used to resize the array
- arange: create a one dimensional array from 0 to number specified
- reshape: change the shape of an array
- itemsize: returns length of each element of array in bytes

In [2]:
import numpy as np
data = [4,7,2,6,7]

data_array = np.array(data, dtype = int, order = "C", ndmin = 2)

print(data)
print(data_array)

[4, 7, 2, 6, 7]
[[4 7 2 6 7]]


In [2]:
#converting nested list into multidimentional array

l = [
    [2,3,4],
    [6,7,8],
    [23,13,5]
]

lr = np.array(l,order = "C")
print(l)
print(lr)

mt_lr = lr * 2
print(mt_lr)

[[2, 3, 4], [6, 7, 8], [23, 13, 5]]
[[ 2  3  4]
 [ 6  7  8]
 [23 13  5]]
[[ 4  6  8]
 [12 14 16]
 [46 26 10]]


In [3]:
mylist = [
          [2,4,6,7,0,3,5],
          [0,1,3,6,7,4,6],
          [1,4,8,2,4,4,11]
]

mylist_array = np.array(mylist)
print(mylist_array)

[[ 2  4  6  7  0  3  5]
 [ 0  1  3  6  7  4  6]
 [ 1  4  8  2  4  4 11]]


In [4]:
#shape of the array
print(mylist_array.shape)

(3, 7)


In [5]:
#resize array
mylist_array.shape = (7,3)
print(mylist_array)

[[ 2  4  6]
 [ 7  0  3]
 [ 5  0  1]
 [ 3  6  7]
 [ 4  6  1]
 [ 4  8  2]
 [ 4  4 11]]


In [6]:
#arange 

'''Creates a one-dimentional array of the specified range'''

new_array = np.arange(12)
print(new_array)
print(new_array.shape)

new_array.shape = (2,6)
print(new_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [7]:
#reshape

'''changes the shape of an array'''

alist = np.arange(18)
print(alist)

#shape of array
print(alist.shape)

#resize
alist.shape = (9,2)
print(alist)

'''n/b: this alters the original shape of the list
#alist.shape = (2,3,3)
#print(alist)'''

#using reshape: this creates a new list of the reshaped list, but still keeps the original list
blist = alist.reshape(2,3,3)
print(blist)

#printing the original
print(alist)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
(18,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


#### Array creation

- empty: Creates an empty array of specified shape
- zeroes: creates an array filled with zeroes
- ones: creates an array filled with ones

In [8]:
#empty array creation

s = np.empty([2,2], dtype = int)
print(s)

[[535705472       250]
 [        0         0]]


In [9]:
d = np.zeros([3,9], dtype = int)
print(d)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [10]:
#arange() - used for creating an array from a range

'''start, stop, step, dtype'''

ex = np.arange(34)
print(ex)

#with dtype
ed = np.arange(34, dtype = float)
print(ed)

#with stop and step
es = np.arange(12,34,2)
print(es)

#linspace: this is used to create a multidimentional array that is equally space
el = np.linspace(12,34,6)#this creates array of numbers(elements) equally spaced from 12 and 34 divided by 6.
print(el)

print(np.__version__)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33.]
[12 14 16 18 20 22 24 26 28 30 32]
[12.  16.4 20.8 25.2 29.6 34. ]
1.16.2


#### Quiz:
1. create an array of range using a number entered by a user
2. convert the array in 1 above to a 2-dimentional array
3. generate another array which is equal of the elements in the array 2 above divided by 0.5

In [15]:
#A program create an array of range using a number entered by a user

number = int(input("Enter a number: "))

num = np.arange(5,number)
print(num)
print(num.shape)

Enter a number: 23
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
(18,)


In [16]:
#converting the array above to a 2-dimentional array

num.shape = (9,2)
print(num)

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]]


In [17]:
#generating another array which is equal of the elements in the array above divided by 0.5

nd = np.arange(5,number,0.5)
print(nd)

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5
 19.  19.5 20.  20.5 21.  21.5 22.  22.5]


In [18]:
#correction for number 3

nd = num/0.5
print(nd)

[[10. 12.]
 [14. 16.]
 [18. 20.]
 [22. 24.]
 [26. 28.]
 [30. 32.]
 [34. 36.]
 [38. 40.]
 [42. 44.]]


#### Slicing
Slicing in python is simply a part of a string, list or array

name = "precious charles"

print(name[4])

output: c

print(name[2:5])

output: reci

N/B: this operation can also be done on mumpy arrays.

In [19]:
a = np.arange(10)
print(a)

#slice
print(a[4]) #print element at index 4

print(a[:4]) #print elements from beginning of array to index 4
print(a[2:4]) #print elements from index 2 to index 5
print(a[2:7:2]) #print elements from index 2 to index 7 step 2

[0 1 2 3 4 5 6 7 8 9]
4
[0 1 2 3]
[2 3]
[2 4 6]


In [20]:
b = a.reshape(5,2)
print(b)

#slicing
print(b[2])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[4 5]


In [21]:
print(b[2:])
print(b[3:4])
print(b[2:5])

[[4 5]
 [6 7]
 [8 9]]
[[6 7]]
[[4 5]
 [6 7]
 [8 9]]


In [22]:
#use of ellipsis in slicing (...)

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print("\n")

print(a[...,1]) #prints all the row elements in column index 1
print("\n")
print(a[1,...]) #prints all the column elements in row index 1

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[2 4 5]


[3 4 5]


In [23]:
#a 3 by 3 array of ones.

x = np.ones([3,3], dtype = int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
#a 3 by 3 array of true values

y = np.empty([3,3], dtype = bool)
print(y)

[[ True  True  True]
 [ True  True False]
 [False False False]]


In [9]:
#second method for the code above

y = np.full(shape = [3,3], dtype = bool, fill_value = True)
print(y)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#an array range from 4 to a number input by the user. Reshaping the array into 2 dimentional array.

new_num = int(input("Enter a number: "))

#for i in range(new_num):
if new_num < 4:
    print("You just entered a number out of range!")
    #break
    exit()
    
elif new_num % 4 != 0:
    print("Sorry!, Try entering a number divisible by 4.")
    #break
    exit()
else:
    print(new_num)
    newarray = np.arange(4,new_num)
    print(newarray)
    
    size = len(newarray)
    print(size)


    #reshape
    newarray.shape = (4, int(size/4))
    print(newarray.shape)
    print(newarray)


Enter a number: 24
24
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
20
(4, 5)
[[ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]]


In [6]:
#an array that satisfies the condition a * b

a = [2,4,5]
b = [[4,5,6], [6,7,8]]

c = np.multiply(a,b)
print(c)

[[ 8 20 30]
 [12 28 40]]


In [7]:
#another method for the calculation in the cell above

a = np.array([2,4,5])
b = np.array([[4,5,6], [6,7,8]])

c = a * b
print(c)


[[ 8 20 30]
 [12 28 40]]
